common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('userinfo/', views.userinfo, name='userinfo'),
    path('userinfo_modify/', views.userinfo_modify, name='userinfo_modify'),
    # path('user_confirm/', views.user_confirm, name='user_confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from trading import views

app_name='trading'

urlpatterns = [
    path('', views.index, name='index'),
    path("admin/", admin.site.urls),
    path('trading/', include('trading.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

trading/urls.py
from django.urls import path
from . import views


app_name = 'trading'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:write_id>/', views.detail, name='detail'),
    path('write/create/', views.write_create, name='write_create'),
    path('answer/create/<int:write_id>/', views.answer_create, name='answer_create'),
]


trading/models.py
from django.db import models

class Write(models.Model):
    subject = models.CharField(max_length=200) # 글 제목
    images = models.ImageField(blank=True, upload_to='images')
    category = models.TextField(default="") # 카테고리
    price = models.IntegerField(default=0) # 가격
    tmethod = models.TextField(default="") # 거래 방식
    content = models.TextField() # 글 내용
    create_date = models.DateTimeField() # 글 작성일

    def __str__(self):
        return self.subject


class Answer(models.Model):
    write = models.ForeignKey(Write, on_delete=models.CASCADE) # 댓글 작성할 글
    content = models.TextField() # 댓글 내용
    create_date = models.DateTimeField() # 댓글 작성

trading/forms.py
from django import forms
from .models import Write, Answer

from django_summernote.widgets import SummernoteWidget

class WriteForm(forms.ModelForm):
    class Meta:
        model = Write
        fields = ['subject', 'content', 'price', 'category', 'tmethod']

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        

trading/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Write, Answer
from django.utils import timezone
from .forms import WriteForm, AnswerForm

def index(request):
    """글 목록 출력"""
    write_list = Write.objects.order_by('-create_date')
    context = {'write_list': write_list}

    return render(request, 'trading/write_list.html', context)

def detail(request, write_id):
    """글 내용 출력"""
    write = get_object_or_404(Write, pk=write_id)
    context = {'write' : write}

    return render(request, 'trading/write_detail.html', context)

def answer_create(request, write_id):
    """댓글 입력"""
    write = get_object_or_404(Write, pk=write_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.write = write
            answer.save()
            return redirect('trading:detail', write_id=write.id)
    else:
        form = AnswerForm()

    context = {'write':write, 'form':form}
    return redirect(request, 'trading/write_detail.html', context)

def write_create(request):
    """글 작성"""
    if request.method == 'POST':
        form = WriteForm(request.POST)
        if form.is_valid():
            write = form.save(commit=False)
            write.price = request.POST.get('price')
            write.tmethod = request.POST.get('tmethod')
            write.category = request.POST.get('category')
            write.images = request.FILES['images']
            write.create_date = timezone.now()
            write.save()
            return redirect('trading:index')
    else:
        form = WriteForm()
        
    context = {'form' : form}
    return render(request, 'trading/write_form.html', context)

templates/trading/write_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ write.subject }}</h2>

    <table class="table_st">
        <tr>
          <td rowspan="4" align="center" style="vertical-align:middle; background-color:white; width:37%;">
            {% if write.images %}
                <img src="{{ write.images.url }}" width="360" height="250">
            {% else %}
                <small>대표 이미지가 존재하지 않습니다.</small>
            {% endif %}
        </td>
          <td class="none_border">&nbsp;</td>
          <td class="boldgray">카테고리</td>
          <td>
            {{ write.category }}
          </td>
        </tr>
        <tr>
          <td class="none_border">&nbsp;</td>
          <td class="boldgray">판매 가격</td>
          <td>
            {% load humanize %}
            {{ write.price|intcomma }} 원
          </td>
        </tr>
        <tr>
          <td class="none_border">&nbsp;</td>
          <td class="boldgray">거래 방식</td>
          <td>
              {{ write.tmethod }}
          </td>
        </tr>
        <tr>
          <td class="none_border">&nbsp;</td>
          <td class="boldgray">판매자 정보</td>
          <td>
            <ul class="list-group list-group-flush" style="margin-left:-18px;">
                <li class="list-group-item">이름: </li>
                <li class="list-group-item">연락처: </li>
                <li class="list-group-item">거래 희망 장소: </li>
            </ul>
          </td>
        </tr>
    </table>
    <div class="card" style='margin-bottom:15px; margin-top:10px; background-color:whitesmoke;'>
      <div class="card-body">
        <h6><b>※ 거래시 필독 사항</b></h6>
        <ul style="list-style-type:square;">
          <li>Trading은 통신판매의 당사자가 아니며 상품정보, 거래에 관한 의무와 책임은 판매자와 구매자에게 있습니다.</li>
          <li>등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 사기통합조회 DB로 수집/활용될 수 있습니다.</li>
          <li>사기피해사례 조회 및 신고는 <a href="https://thecheat.co.kr/rb/?mod=_search" target='_blank'>더치트</a>에서 확인해주세요.</li>  
        </ul>
      </div>
    </div>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ write.content|safe }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ write.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">
        댓글 <b>{{write.answer_set.count}}</b>
    </h5>

    {% for answer in write.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ answer.content }}
            </div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <form action="{% url 'trading:answer_create' write.id %}" method="post" class="my-3">
        {% csrf_token %}

        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}

        <div class="form-group">
        <textarea name="content" id="content" class="form-control" rows="4"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary" style="float:right; margin-bottom:30px;">
    </form>
</div>
{% endblock %}

templates/trading/write_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2"><b>글쓰기</b></h5>
  <form method="post" class="post-form my-3" enctype='multipart/form-data'>
    {% csrf_token %}

    <!-- 오류표시 Start -->
    {% if form.errors %}
      <div class="alert alert-danger" role="alert">
      {% for field in form %}
        {% if field.errors %}
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
        {% endif %}
      {% endfor %}
      </div>
    {% endif %}
    <!-- 오류표시 End -->

    <div class="form-group">
      <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}" placeholder="제목을 입력하세요.">
    </div>
    <div class="form-group">
      <table class="table_st">
        <tr>
          <td rowspan="4" align="center" style="vertical-align:middle; width:37%;">
            <img id="previewImg" class='upload' width="360px" height="200px" alt="여기를 클릭해 대표 이미지를 등록해주세요."/>
            <input type="file" class='real-upload' id="fileUpload" name="images" accept="image/*" style="float:right; display:none;" required>
          </td>
          <td class="none_border">&nbsp;</td>
          <td class="boldgray">카테고리</td>
          <td>
            <div>
                <select class="form-control" id="exampleFormControlSelect1"  name="category" required>
                  <option selected>카테고리를 선택하세요.</option>
                  <option value="가전제품">가전제품</option>
                  <option value="전자기기">전자기기</option>
                  <option value="의류">의류</option>
                  <option value="잡화">잡화</option>
                  <option value="무료 나눔">무료 나눔</option>
                </select>
              </div>
          </td>
        </tr>
        <tr>
          <td class="none_border">&nbsp;</td>
          <td class="boldgray">판매 가격</td>
          <td>
            <input type="number" min='3000' max='100000000' style="width:50%;" name='price' id='price' required></input>&nbsp;원
          </td>

        </tr>
        <tr>
          <td class="none_border">&nbsp;</td>
          <td class="boldgray">거래 방식</td>
          <td>
            <div class="btn-group btn-group-toggle" data-toggle="buttons">
              <label class="btn btn-outline-secondary active">
                <input type="radio" name="tmethod" id="option1" value="택배 및 직거래" checked> 택배/직거래
              </label>
              <label class="btn btn-outline-secondary">
                <input type="radio" name="tmethod" id="option2" value="택배 거래"> 택배 거래
              </label>
              <label class="btn btn-outline-secondary">
                <input type="radio" name="tmethod" id="option3" value="직거래"> 직거래
              </label>
            </div>
          </td>
        </tr>
        <tr>
          <td class="none_border">&nbsp;</td>
          <td class="boldgray">판매자 정보</td>
          <td>
            <ul class="list-group list-group-flush" style="margin-left:-18px;">
                <li class="list-group-item">이름: </li>
                <li class="list-group-item">연락처: </li>
                <li class="list-group-item">거래 희망 장소: </li>
            </ul>
          </td>
        </tr>
      </table>
    </div>
    <div class="card" style='margin-bottom:15px; background-color:whitesmoke;'>
      <div class="card-body">
        <h6><b>※ 거래시 필독 사항</b></h6>
        <ul style="list-style-type:square;">
          <li>Trading은 통신판매의 당사자가 아니며 상품정보, 거래에 관한 의무와 책임은 판매자와 구매자에게 있습니다.</li>
          <li>등록한 게시글이 회원의 신고를 받거나 이상거래로 모니터링 될 경우 사기통합조회 DB로 수집/활용될 수 있습니다.</li>
          <li>사기피해사례 조회 및 신고는 <a href="https://thecheat.co.kr/rb/?mod=_search" target='_blank'>더치트</a>에서 확인해주세요.</li>  
        </ul>
      </div>
    </div>
    <div class="form-group">
      <textarea class="form-control" name="content" id="summernote">{{form.content.value|default_if_none:''}}</textarea>
    </div>
    <button type="submit" class="btn btn-primary" style="float:right">저장하기</button>
  </form>
</div>
{% endblock %}

{% block script %}
<script>
  // 대표 이미지 등록 스크립트 
  const fileInput = document.getElementById("fileUpload");

  const handleFiles = (e) => {
    const selectedFile = [...fileInput.files];
    const fileReader = new FileReader();

    fileReader.readAsDataURL(selectedFile[0]);

    fileReader.onload = function () {
      document.getElementById("previewImg").src = fileReader.result;
    };
  };

  fileInput.addEventListener("change", handleFiles);

  // 대표 이미지 type:file 숨기기
  const realUpload = document.querySelector('.real-upload');
  const upload = document.querySelector('.upload');
  upload.addEventListener('click', () => realUpload.click());

  // 뒤로가기 확인


  // 써머노트 기능 
  $('#summernote').summernote({
    placeholder: '내용을 입력하세요.',
    lang: "ko-KR",
    tabsize: 2,
    height: 700,
    focus: true,
    defaultFontName: '바탕체',
    toolbar: [
    ['style', ['style']],
    ['fontname', ['fontname']],
    ['fontsize', ['fontsize']],
    ['font style', ['bold', 'italic', 'underline','strikethrough', 'clear']],
    ['color', ['forecolor','color']],
    ['para', ['ul', 'ol', 'paragraph']],
    ['table', ['table']],
    ['insert', ['link', 'picture', 'video']],
    ['view', ['fullscreen', 'codeview', 'help']],
  ],
    defaultFontName:'바탕',
    fontNames: ['Arial', 'Arial Black', 'Comic Sans MS','맑은 고딕','궁서','굴림','돋음체','바탕'],
    fontSizes: ['8','9','10','11','12','14','16','18','20','22','24','28','30','36','50','72'],

    popover: {
        image: [
          ['image', ['resizeFull', 'resizeHalf', 'resizeQuarter', 'resizeNone']],
          ['float', ['floatLeft', 'floatRight', 'floatNone']],
          ['remove', ['removeMedia']]
        ],
        link: [
          ['link', ['linkDialogShow', 'unlink']]
        ],
        table: [
          ['add', ['addRowDown', 'addRowUp', 'addColLeft', 'addColRight']],
          ['delete', ['deleteRow', 'deleteCol', 'deleteTable']],
        ],
        air: [
          ['color', ['color']],
          ['font', ['bold', 'underline', 'clear']],
          ['para', ['ul', 'paragraph']],
          ['table', ['table']],
          ['insert', ['link', 'picture']]
        ]
      }
      
    
  });

</script>
{% endblock script %} 

templates/trading/write_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
            <tr class="thead-dark">
                <th>번호</th>
                <th>제목</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        {% if write_list %}
            {% for write in write_list %}
                <tr>
                    <td>
                        {{ forloop.counter }}
                    </td>
                    <td>
                    <a href="{% url 'trading:detail' write.id %}">{{ write.subject }}</a>
                    </td>
                    <td>
                    {{ write.create_date }}
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
        {% endif %}
        </tbody>
    </table>

    <a href="{% url 'trading:write_create' %}" class="btn btn-primary">질문 등록하기</a>

</div>
{% endblock %}