common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('userinfo/', views.userinfo, name='userinfo'),
    path('userinfo_modify/', views.userinfo_modify, name='userinfo_modify'),
    # path('user_confirm/', views.user_confirm, name='user_confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from trading import views

app_name='trading'

urlpatterns = [
    path('', views.index, name='index'),
    path("admin/", admin.site.urls),
    path('trading/', include('trading.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login_out/urls.py
from django.urls import path
from . import views


app_name = 'login_out'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
]

login_out/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

login_out/views.py
from django.shortcuts import render, get_object_or_404
from .models import Question

# Create your views here.



def index(request):
    """
    pybo 목록 출력
    """
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    
    return render(request, 'login_out/question_list.html', context)



def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'login_out/question_detail.html', context)

templates/login_out/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<h1>{{ question.subject }}</h1>
<div>
{{ question.content }}
</div>

templates/login_out/question_list.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

{% block content %}

{% if question_list %}
<ul>
    {% for question in question_list %}
    <!-- <li><a href="/login_out/{{ question.id }}/">{{ question.subject }}<a/></li> -->
    <li><a href="{% url 'login_out:detail' question.id %}">{{ question.subject }}<a/></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}

{% endblock content %}