common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('userinfo/', views.userinfo, name='userinfo'),
    path('userinfo_modify/', views.userinfo_modify, name='userinfo_modify'),
    # path('user_confirm/', views.user_confirm, name='user_confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from trading import views

app_name='trading'

urlpatterns = [
    path('', views.index, name='index'),
    path("admin/", admin.site.urls),
    path('trading/', include('trading.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

common/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, AbstractUser


class UserManager(BaseUserManager):
    def create_user(self, email, nickname=None, username=None, profile_image=None, phonenumber=None, address=None, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            nickname = nickname,
            username = username,
            profile_image = profile_image,
            phonenumber = phonenumber,
            address = address,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nickname=None, username=None, profile_image=None, phonenumber=None, address=None, password=None):
        user = self.create_user(
            email,
            password=password,
            nickname = nickname,
            username = username,
            profile_image = profile_image,
            phonenumber = phonenumber,
            address = address,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractUser):
    email = models.EmailField(verbose_name='email', max_length=255, unique=True,)
    nickname = models.CharField(max_length=24, default=None, null=True, blank=True, unique=True)
    username = models.CharField(max_length=24, default=None, null=True, blank=True)
    profile_image = models.TextField(default=None, null=True, blank=True)
    phonenumber = models.IntegerField(default=None, null=True, unique=True, blank=True)
    address = models.TextField(default=None, null=True, blank=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nickname']

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

# from django.db import models
# from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# from django.contrib.auth.base_user import AbstractBaseUser


# class User(AbstractBaseUser):
#     """
#     이메일 = email
#     PW = password1
#     PW확인 = password2
#     닉네임 = nickname
#     이름 = username
#     프로필 이미지 = profile_image
#     전화번호 = phonenumber
#     주소 = address
#     """

#     email = models.EmailField()
#     nickname = models.CharField(max_length=24)
#     username = models.CharField(max_length=24)
#     profile_image = models.TextField()
#     phonenumber = models.CharField(max_length=24)
#     address = models.TextField()

#     class Meta:
#         db_table = "User"




# class User(AbstractBaseUser):
#     """
#     ID = userid
#     PW = password1
#     PW확인 = password2
#     닉네임 = nickname
#     이름 = username
#     전화번호 = phonenumber
#     주소 = address
#     """
#     email = models.EmailField(
#         verbose_name='email',
#         max_length=255,
#         unique=True,
#     )
#     date_of_birth = models.DateField()
#     is_active = models.BooleanField(default=True)
#     is_admin = models.BooleanField(default=False)

#     objects = UserManager()

#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = ['date_of_birth']

#     def __str__(self):
#         return self.email

#     def has_perm(self, perm, obj=None):
#         return True

#     def has_module_perms(self, app_label):
#         return True

#     @property
#     def is_staff(self):
#         return self.is_admin






# class User(AbstractBaseUser):
#     # Default : id / password / last_login
#     # USER_TYPE_CHOICES = (
#     #     ('django', 'Django'),
#     #     ('django', 'Django'),
#     #     ('django', 'Django'),
#     # )
#     pass

# class UserManager(BaseUserManager):
#     def _create_user(self, email, username, password, gender = 1, **extra_fields):
#         if not email :
#             raise ValueError('The given email mist be set')
#         email = self.normalize_email(email)
#         username = self.model.normalize_username(username)
#         user = self.model(email = email, username = username, gender=gender, **extra_fields)
#         user.set_password(password)
#         user.save (using = self._db)
#         return user

#     def create_user(self, email, username = '', password = None, **extra_fields):
#         extra_fields.setdefault('is_staff', False)
#         extra_fields.setdefault('is_superuser', False)
#         return self._create_user(email, username, password, **extra_fields)
    
#     def create_superuser(self, email, password, **extra_fields):
#         extra_fields.setdefault('is_staff', True)
#         extra_fields.setdefault('is_superuser', True)

#         if extra_fields.get('is_staff') is not True:
#             raise ValueError('Superuser must have is_staff = True')
#         if extra_fields.get('is_superuser') is not True:
#             raise ValueError('Superuser must have is_superuser = True')

#         return self._create_user(email, username, password, **extra_fields)

# GENDER_CHOICES = (
#     (0, 'Female'),
#     (1, 'Male'),
#     (2, 'Not to disclose')
# )

# class User(AbstractUser):
#     email = models.EmailField(verbose_name = "email", max_length = 255, unique = True)
#     username = models.CharField(max_length=30)
#     gender = models.SmallIntegerField(choices = GENDER_CHOICES)
#     objects = UserManager()
#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = []

#     def __str__(self):
#         return "<%d %s>" %(self.pk, self.email)

common/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email', 'nickname', 'username', 'phonenumber', 'address')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    # password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'nickname', 'username', 'phonenumber', 'address', 
                  'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]



# from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
# from django.db import models


# from django import forms
# from django.contrib.auth.forms import ReadOnlyPasswordHashField

# from .models import User


# class UserCreationForm(forms.ModelForm):
#     password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
#     password2 = forms.CharField(
#         label='Password confirmation', widget=forms.PasswordInput)

#     class Meta:
#         model = User
#         fields = ('email', 'date_of_birth')

#     def clean_password2(self):
#         password1 = self.cleaned_data.get("password1")
#         password2 = self.cleaned_data.get("password2")
#         if password1 and password2 and password1 != password2:
#             raise forms.ValidationError("Passwords don't match")
#         return password2

#     def save(self, commit=True):
#         user = super().save(commit=False)
#         user.set_password(self.cleaned_data["password1"])
#         if commit:
#             user.save()
#         return user


# class UserChangeForm(forms.ModelForm):
#     password = ReadOnlyPasswordHashField()

#     class Meta:
#         model = User
#         fields = ('email', 'password', 'date_of_birth',
#                   'is_active', 'is_admin')

#     def clean_password(self):
#         return self.initial["password"]


# class UserForm(models.Model):
#     # email = forms.EmailField(label="이메일")
    
#     # class Meta:
#         # model = User
#         # fields = ("username", "email")
#     fields = ['userid', 'password', 'nickname', 'username', 'phonenumber', 'address']
#     widgets = {
#         'userid': forms.TextInput(attrs={'placeholder': '아이디를 입력하세요.'}),
#         'password': forms.TextInput(attrs={'placeholder': '비밀번호를 입력하세요.'}),
#         'nickname': forms.TextInput(attrs={'placeholder': '별명을 입력하세요.'}),
#         'username': forms.TextInput(attrs={'placeholder': '본인의 이름을 입력하세요.'}),
#         'phonenumber': forms.TextInput(attrs={'placeholder': '전화번호를 입력하세요.'}),
#         'address': forms.TextInput(attrs={'placeholder': '주소를 입력하세요.'}),
#     }

common/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
# from common.forms import UserForm
from common.forms import UserCreationForm
from .models import User
from .forms import UserChangeForm

def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(email=email, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'common/signup.html', {'form': form})




# def login(request):
#     """
#     로그인
#     """
#     print(request)
#     print(request.email)
#     user = authenticate(email=request.email, password=request.raw_password)
#     login(request, user)

#     return redirect('index')


# def user_confirm(request):
#     """
#     유저 정보 전 인증
#     """
#     return render(request, 'common/user_confirm.html')

def userinfo(request):
    """
    유저 정보
    """
    return render(request, 'common/userinfo.html')


def userinfo_modify(request):
    """
    유저 정보 수정
    """
    user = get_object_or_404(User, pk=request.user.id)
    if request.method == "POST":
        # 질문 수정을 위해 값 덮어쓰기
        form = UserChangeForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect('index')
    else:
        # 질문 수정 화면에 기존 제목, 내용 반영
        form = UserChangeForm(instance=user)

    context = {'form':form}
    return render(request, 'common/userinfo_modify.html', context)















































# def signup(request):
#     """
#     계정생성
#     """
#     if request.method == "POST":
#         form = UserForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             raw_password = form.cleaned_data.get('password1')
#             user = authenticate(username=username, password=raw_password)
#             login(request, user)
#             return redirect('index')
#     else:
#         form = UserForm()
#     return render(request, 'common/signup.html', {'form': form})


# def userinfo(request):
#     """
#     유저 정보
#     """
#     return render(request, 'common/userinfo.html')

# def userinfo(request, user_id):
#     """
#     유저 정보
#     """
#     username = get_object_or_404(User, pk=user_id)
#     context = {'username': username}
#     return render(request, 'login_out/question_detail.html', context)


# def detail(request, question_id):
#     """
#     pybo 내용 출력
#     """
#     question = get_object_or_404(Question, pk=question_id)
#     context = {'question': question}
#     return render(request, 'login_out/question_detail.html', context)


# @login_required(login_url='common:login')
# def question_modify(request, question_id):
#     """
#     pybo 질문수정
#     """
#     question = get_object_or_404(Question, pk=question_id)
#     if request.user != question.author:
#         messages.error(request, '수정권한이 없습니다')
#         return redirect('pybo:detail', question_id=question_id)

#     if request.method == "POST":
#         # 질문 수정을 위해 값 덮어쓰기
#         form = QuestionForm(request.POST, instance=question)
#         if form.is_valid():
#             question = form.save(commit=False)
#             question.author = request.user
#             question.modify_date = timezone.now()   # 수정일시 저장
#             question.save()
#             return redirect('pybo:detail', question_id=question.id)
#     else:
#         # 질문 수정 화면에 기존 제목, 내용 반영
#         form = QuestionForm(instance=question)

#     context = {'form':form}

#     return render(request, 'pybo/question_form.html', context)

templates/common/login.html
{% extends "base.html" %}
{% block content %}
  <div class="container my-3">
    <div class="row">
      <div class="col-4">
        <h4>로그인</h4>
      </div>
      <div class="col-8 text-right">
        또는
        <a href="{% url 'common:signup' %}">계정을 만드세요.</a>
      </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
      {% csrf_token %}
      {% include "form_errors.html" %}
      <div class="form-group">
        <label for="username">이메일</label>
        <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="password">비밀번호</label>
        <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
      </div>
      <button type="submit" class="btn btn-primary">로그인</button>
      
    </form>
  </div>
{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
  <div class="container my-3">
    <div class="row my-3">
      <div class="col-4">
        <h4>계정생성</h4>
      </div>
      <div class="col-8 text-right">
        또는
        <a href="{% url 'common:login' %}">로그인 하세요.</a>
      </div>
    </div>
    <form method="post" class="post-form">
      {% csrf_token %}
      {% include "form_errors.html" %}
      <div class="form-group">
        <label for="email">이메일</label>
        <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="password1">비밀번호</label>
        <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="password2">비밀번호 확인</label>
        <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="nickname">닉네임</label>
        <input type="text" class="form-control" name="nickname" id="nickname" value="{{ form.nickname.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="username">이름</label>
        <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="phonenumber">전화번호</label>
        <input type="text" class="form-control" name="phonenumber" id="phonenumber" value="{{ form.phonenumber.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="address">주소</label>
        <input type="text" class="form-control" name="address" id="address" value="{{ form.address.value|default_if_none:'' }}">
      </div>
      <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
  </div>
{% endblock %}

templates/common/user_confirm.html
<!--
{% extends "base.html" %}
{% block content %}
  <div class="container my-3">
    <div class="row">
        비밀번호를 입력하세요.
    </div>
    <form method="post" class="post-form" action="{% url 'common:' %}">
      {% csrf_token %}
      {% include "form_errors.html" %}
      <div class="form-group">
        <label for="password">비밀번호</label>
        <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
      </div>
      <button type="submit" class="btn btn-primary">입력</button>
    </form>
  </div>
{% endblock %}
-->

templates/common/userinfo.html
{% extends 'base.html' %}
{% block content %}
  <div>
    <div>
      <div>
        이메일
        {{ user.email }}
      </div>
      <div>
        닉네임
        {{ user.nickname }}
      </div>
    </div>

    <div>
      이름
      {{ user.username }}
    </div>
    <div>
      전화번호
      {{ user.phonenumber }}
    </div>
    <div>
      주소
      {{ user.address }}
    </div>
  </div>

  <a href="{% url 'common:userinfo_modify' %}" class="btn btn-sm btn-outline-secondary">수정</a>
  {% comment %} <div class="my-3">
    <a href="{% url 'pybo:question_modify' question.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
  </div> {% endcomment %}
{% endblock content %}

templates/common/userinfo_modify.html
{% extends "base.html" %}
{% block content %}
  <div class="container my-3">
    <form method="post" class="post-form">
      {% csrf_token %}
      {% include "form_errors.html" %}
      <div class="form-group">
        <label for="email">이메일</label>
        <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}" readonly>
      </div>
      <div class="form-group">
        <label for="nickname">닉네임</label>
        <input type="text" class="form-control" name="nickname" id="nickname" value="{{ form.nickname.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="username">이름</label>
        <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="phonenumber">전화번호</label>
        <input type="text" class="form-control" name="phonenumber" id="phonenumber" value="{{ form.phonenumber.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="address">주소</label>
        <input type="text" class="form-control" name="address" id="address" value="{{ form.address.value|default_if_none:'' }}">
      </div>
      <button type="submit" class="btn btn-primary">수정하기</button>
    </form>
  </div>
{% endblock %}