common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),

    path('userinfo/', views.userinfo, name='userinfo'),
    path('userinfo_modify/', views.userinfo_modify, name='userinfo_modify'),
    # path('user_confirm/', views.user_confirm, name='user_confirm'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from trading import views

app_name='trading'

urlpatterns = [
    path('', views.index, name='index'),
    path("admin/", admin.site.urls),
    path('trading/', include('trading.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

joonggo/urls.py
from django.urls import path
from .views import base_views, sell_views, comment_views, vote_views


app_name = 'joonggo'

urlpatterns = [
    path('', base_views.index, name='index'),
    path('<int:sell_id>/', base_views.detail, name='detail'),

    path('comment/create/sell/<int:sell_id>/', comment_views.comment_create_sell, name='comment_create_sell'),
    path('comment/modify/sell/<int:comment_id>/', comment_views.comment_modify_sell, name='comment_modify_sell'),
    path('comment/delete/sell/<int:comment_id>/', comment_views.comment_delete_sell, name='comment_delete_sell'),
    

    path('question/create/', sell_views.sell_create, name='sell_create'),
    path('question/modify/<int:sell_id>/', sell_views.sell_modify, name='sell_modify'),
    path('question/delete/<int:sell_id>/', sell_views.sell_delete, name="sell_delete"),
    path('question/mypost/<int:sell_id>/', sell_views.sell_mypost, name="sell_mypost"),
    path('question/mylike/<int:sell_id>/', sell_views.sell_mylike, name="sell_mylike"),

    path('vote/question/<int:sell_id>/', vote_views.vote_sell, name='vote_sell'),

]

trading/models.py
from django.db import models

class Write(models.Model):
    subject = models.CharField(max_length=200) # 글 제목
    images = models.ImageField(blank=True, upload_to='images')
    category = models.TextField(default="") # 카테고리
    price = models.IntegerField(default=0) # 가격
    tmethod = models.TextField(default="") # 거래 방식
    content = models.TextField() # 글 내용
    create_date = models.DateTimeField() # 글 작성일

    def __str__(self):
        return self.subject


class Answer(models.Model):
    write = models.ForeignKey(Write, on_delete=models.CASCADE) # 댓글 작성할 글
    content = models.TextField() # 댓글 내용
    create_date = models.DateTimeField() # 댓글 작성

joonggo/forms.py
from django import forms
from joonggo.models import Sell, Comment
from django.contrib.auth.models import User

class SellForm(forms.ModelForm):
    class Meta:
        model = Sell
        fields = ['subject', 'content']
        lables = {
            'subject': '제목',
            'content': '내용',
        }

        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows':10}),   
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
        'content': '댓글내용',
        }

joonggo/views/mypost_views.py
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Sell

from django.db.models import Q
from django. contrib.auth.decorators import login_required

from django.core.paginator import Paginator

@login_required(login_url='common:login')
def sell_mypost(request, sell_id):
    """
    joonggo 목록 출력
    """
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    
    sell_list = Sell.objects.order_by('-create_date')
    if kw:
        sell_list = sell_list.filter(
            Q(subject__icontains=kw) | #제목 검색
            Q(content__icontains=kw) | #내용 검색
            Q(author__username__icontains=kw)
        )
   
    paginator = Paginator(sell_list, 12)
    page_obj = paginator.get_page(page)

    context = {'sell_list': page_obj,
               'page': page,
               'kw': kw,
               }
    
    return render(request, 'joonggo/sell_mypost.html', context)

joonggo/views/sell_views.py
from django.shortcuts import render, get_object_or_404, redirect
from ..models import Sell
from django.utils import timezone
from ..forms import SellForm

from django.db.models import Q
from django. contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator

# Create your views here.
@login_required(login_url='common:login')
def sell_create(request):
    """
    joonggo 글작성
    """
    if request.method == 'POST':
        
        form = SellForm(request.POST)
        if form.is_valid():
            sell = form.save(commit=False)
            sell.author = request.user
            sell.create_date = timezone.now()
            sell.save()
            return redirect('joonggo:index')
    else:
        form = SellForm()
    
    context = {'form': form}
    return render(request, 'joonggo/sell_form.html', context)

@login_required(login_url='common:login')
def sell_modify(request, sell_id):
    """
    joonggo 작성글 수정
    """
    sell = get_object_or_404(Sell, pk=sell_id)
    if request.user != sell.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('joonggo:detail', sell_id=sell.id)

    if request.method == "POST":
        form = SellForm(request.POST, instance=sell)
        if form.is_valid():
            sell = form.save(commit=False)
            sell.author = request.user
            sell.modify_date = timezone.now()
            sell.save()
            return redirect('joonggo:detail', sell_id=sell.id)
    else:
        form = SellForm(instance=sell)

    context = {'form': form}
    return render(request, 'joonggo/sell_form.html', context)

@login_required(login_url='common:login')
def sell_delete(request, sell_id):
    """
    joonggo 작성글 삭제
    """
    sell = get_object_or_404(Sell, pk=sell_id)
    if request.user != sell.author:
        messages.error(request, '글삭제권한이 없습니다')
        return redirect('joonggo:detail', sell_id=sell.id)
    sell.delete()
    return redirect('joonggo:index')


@login_required(login_url='common:login')
def sell_mypost(request, sell_id):
    """
    joonggo 목록 출력
    """
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    
    # sell_list = Sell.objects.order_by('-create_date')
    sell_list = request.user.author_sell.order_by('-create_date')
    if kw:
        sell_list = sell_list.filter(
            Q(subject__icontains=kw) | #제목 검색
            Q(content__icontains=kw) | #내용 검색
            Q(author__username__icontains=kw)
        ).distinct()
   
    paginator = Paginator(sell_list, 12)
    page_obj = paginator.get_page(page)

    context = {'sell_list': page_obj,
               'page': page,
               'kw': kw,
               }
    
    return render(request, 'joonggo/sell_mypost.html', context)

@login_required(login_url='common:login')
def sell_mylike(request, sell_id):
    """
    joonggo 목록 출력
    """
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    
    # sell_list = Sell.objects.order_by('-create_date')
    sell_list = request.user.voter_sell.order_by('-create_date')
    if kw:
        sell_list = sell_list.filter(
            Q(subject__icontains=kw) | #제목 검색
            Q(content__icontains=kw) | #내용 검색
            Q(author__username__icontains=kw)
        ).distinct()
   
    paginator = Paginator(sell_list, 12)
    page_obj = paginator.get_page(page)

    context = {'sell_list': page_obj,
               'page': page,
               'kw': kw,
               }
    
    return render(request, 'joonggo/sell_mylike.html', context)

joonggo/views/vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect

from ..models import Sell


@login_required(login_url='common:login')
def vote_sell(request, sell_id):
    """
    joonggo 작성글 추천
    """
    sell = get_object_or_404(Sell, pk=sell_id)
    if request.user == sell.author:
        messages.error(request, '본인이 작성한 글은 좋아요할 수 없습니다.')
    elif request.user in sell.voter.all():
        sell.voter.remove(request.user)    
    else:
        sell.voter.add(request.user)
    return redirect('joonggo:detail', sell_id=sell.id)

templates/joonggo/pagenation.html
<!-- 페이지 번호 등록 -->
<ul class="pagination justify-content-center">
<!-- 이전 페이지 -->
{% if sell_list.has_previous %}
    <li class="page-item">
        <a class="page-link" href="#"
        data-page="1">
            <i class="fa-solid fa-angles-left"></i>
        </a>
    </li>
    <li class="page-item">
        <a class="page-link" 
            href="#" data-page="{{ sell_list.previous_page_number}}"><i class="fa-solid fa-chevron-left"></i></a>
    </li>

{% else %}
    <li class="page-item disabled">
        <a class="page-link" href="?page=1">
            <i class="fa-solid fa-angles-left"></i>
        </a>
    </li>
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#"><i class="fa-solid fa-chevron-left"></i></a>
    </li> <!-- tabindex="-1"은 tab으로 이동시 선택되지 않는것을 의미.
             aria-disabled="true"는 시각장애인들을 위한 청각적 도움을 줌 -->

{% endif %}
  <!-- 페이지 리스트 -->
{% for page_number in sell_list.paginator.page_range %}

    {% if page_number >= sell_list.number|add:-3 and page_number <= sell_list.number|add:3 %}
  <!-- 템플릿을 사용할 땐 한줄로 작성해야 하고, |필터를 사용할 때 공백이 들어가면 안됨.
    formatter를 쓰면 공백을 자동으로 추가해서 에러가 발생함-->
        {% if page_number == sell_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="#" data-page="{{ page_number }}">{{ page_number }}</a>
            </li>
        {% else %}
            <li class="page-item">
                <a class="page-link" href="#" data-page="{{ page_number }}">{{ page_number }}</a>
            </li>
        {% endif %}
    {% endif %}  
{% endfor %}

  <!-- 다음 페이지 -->
{% if sell_list.has_next %}
<li class="page-item">
    <a class="page-link" href="#" data-page="{{ sell_list.next_page_number}}">
        <i class="fa-solid fa-chevron-right"></i>
    </a>
</li>
<li class="page-item">
    <a class="page-link" href="#" data-page="{{ sell_list.paginator.num_pages}}">
        <i class="fa-solid fa-angles-right"></i>
    </a>
</li>

{% else %}  
    <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
            <i class="fa-solid fa-chevron-right"></i>
        </a>
    </li>
    <li class="page-item disabled">
        <a class="page-link" href="#" data-page="{{ sell_list.paginator.num_pages}}">
            <i class="fa-solid fa-angles-right"></i>
        </a>
    </li>
  <!-- tabindex="-1"은 tab으로 이동시 선택되지 않는것을 의미. aria-disabled="true"는 시각장애인들을 위한 청각적 도움을 줌 -->
{% endif %}
</ul>

templates/joonggo/sell_detail.html
{% extends 'base.html' %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

{% block content %}
  <div class="container my-3">
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
      {% for message in messages %}
      <strong>{{ message.tags }}</strong>
      <ul><li>{{ message.message}}</li></ul>
      {% endfor %}
    </div>
    {% endif %}
    
    <h2 class="border-bottom py-2">{{ sell.subject }}</h2>
    <div class="row my-3">
      <div class="col-1.5">
        <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
          {{ sell.voter.count }}</div>
        {% comment %} <a href="#" data-uri="{% url 'joonggo:vote_sell' sell.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">좋아요</a> {% endcomment %}
        {% if user in sell.voter.all %}
        <a href="#" data-uri="{% url 'joonggo:vote_sell' sell.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1"><i class="fa-solid fa-heart"></i> 좋아요</a>
        {% else %}
        <a href="#" data-uri="{% url 'joonggo:vote_sell' sell.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1"><i class="fa-regular fa-heart"></i> 좋아요</a>
        {% endif %}
        </div>
      <div class="col-11">
        {% comment %} 가격 : <span class="price" style="white-space: pre-line;">{{ sell.price }}</span> {% endcomment %}
        <div class="card">
          {% autoescape off %}
          <div class="card-text" style="white-space: pre-line;">{{ sell.content }}</div>
          {% endautoescape %}
          
          <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2 text-left">
              <div class="mb-2">{{ sell.author.username }}</div>
              <div>{{ sell.create_date|date:"Y-m-d H:i" }}</div>
            </div>
          </div>
        </div>
        {% if request.user == sell.author %}
        <div class="my-3" align="right">
          <a href="{% url 'joonggo:sell_modify' sell.id %}" class="btn btn-sm btn-outline-secondary">수정</a>
          <a href="#" class="delete btn btn-sm btn-outline-secondary" data-uri="{% url 'joonggo:sell_delete' sell.id %}">삭제</a>
        </div>
        {% endif %}
        {% if sell.comment_set.count > 0 %}
        <div class="mt-3">
        {% for comment in sell.comment_set.all %}
          <div class="comment py-2">
            <span style="white-space: pre-line;">{{ comment.content }}</span>
            <span>
              - {{ comment.author }}, {{ comment.create_date }}
              {% if comment.modify_date %}
              (수정: {{ comment.modify_date }})
              {% endif %}
            </span>
            {% if request.user == comment.author %}
              <a href="{% url 'joonggo:comment_modify_sell' comment.id %}" class="small">수정</a>
              <a href="#" class="small delete" data-uri="{% url 'joonggo:comment_delete_sell' comment.id %}">삭제</a>
            {% endif %}
          </div>
        {% endfor %}
        </div>
        {% endif %}
        <div>
          <a href="{% url 'joonggo:comment_create_sell' sell.id %}"
          class="small"><small>댓글 달기</small></a>
        </div>
    </div>

{% endblock content %}

{% block script %}
<script>
  $(document).ready(function () {
    console.log('로딩 완료');
    let btns = $('.delete') // 변수 선언 키워드 let
    btns.on('click', function () { // .on('이벤트이름', 이벤트핸들러)
      console.log('click 발생');
      let answer = confirm('정말 삭제할까요?');
      if (answer) {
        location.href = $(this).data('uri'); // this: click이벤트를 발생한 인스턴스에 대한 참조
      }
    }); // 변수 선언 키워드 let
    $(".recommend").on('click', function () {
      if (confirm("정말로 추천하시겠습니까?")) {
        location.href = $(this).data('uri');
      } 
      
    })

    console.log('click 이벤트 핸들러 등록 완료')
  });
</script>

{% endblock script %}

templates/joonggo/sell_form.html
{% extends 'base.html' %}
{% load static %}

{% load bootstrap4 %}

{% block style %}
  <link rel="stylesheet"   href="{% static 'summernote-bs4.min.css' %}">
{% endblock style %}

{% block script %}
<script src="{% static 'summernote-ko-KR.min.js' %}"></script>
<script src="{% static 'summernote-bs4.min.js' %}"></script>

<script>
  $(function(){
    $('#id_content').summernote({
        height: 300,
    });
  });
  </script>
{% endblock script %}





{% block content %}
  <h5 class='my-3 border-bottom pb-2'>
    <i class="fa-solid fa-pen-to-square"></i>
    게시글 작성</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}
    
    {% bootstrap_form form %}
    {% comment %} {{ form.as_p}} {% endcomment %}
    {% comment %} {% if form.errors %}
      <div class="alert alert-danger" role="alert">
        {% for field in form %}
          {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
          {% endif %}
        {% endfor %}
      </div>
    {% endif %}
    <div class="form-group">
      <label for="id_subject">제목</label>
      <input type="text" class="form-control" name="subject" id="id_subject" value="{{ form.subject.value|default_if_none:'' }}">
      {% if form.subject.errors %}
        <div class="text-danger">
          {% for error in form.subject.errors%}
            <div>
              <i class="fa-solid fa-triangle-exclamation"></i>
              {{error}}
            </div>
          {% endfor %}
        </div>
      {% endif %}
    </div>
    <div class="form-group">
      <label for="content">내용</label>
      <textarea class="form-control" name="content" id="content" rows="10">{{form.content.value|default_if_none:''}}</textarea>

    </div> {% endcomment %}

    <button type="submit" class="btn btn-primary">저장하기</button>
    <a href="{% url 'joonggo:index' %}" class="btn btn-primary">
      <i class="fa-solid fa-list"></i>
      목록으로
    </a>
  </form>

{% endblock content %}

templates/joonggo/sell_list.html
{% extends 'base.html' %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

{% block content %}

<div class="row ml-5 my-3">
  <div class="col-2">
    <div class='card'>
      <div class="card-body">
        {% if user.is_authenticated %}
        <div>회원정보</div>
        <img class="avatar" src="https://randomuser.me/api/portraits/men/{{user.id}}.jpg"> {{ user.username }}
        <div>
          <a style="color:black;" href="{% url 'joonggo:sell_mypost' user.id %}">내가 쓴 글 보기</a>
        </div>
        <div>
          <a style="color:black;" href="{% url 'joonggo:sell_mylike' user.id %}">좋아요 한 글 보기</a>
        </div>
        {% else %}
        <div>
        회원정보
        </div>
        <a style="font-size:14px;" class="nav-link" href="{% url 'common:login' %}">로그인이 필요합니다.</a>
        {% endif %}
      </div>
    </div>
  </div>
  
  <div class="col-8 mr-3">
    <table class="table">

      <tbody>
        

        <!-- 게시판 카드형식 만들기 -->
        <div class="container">
          <div class="row justify-content-center my-3">
            <div class="col-6 input-group">
              <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
              <div class="input-group-append">
                <button class="btn btn-outline-dark" type="button" id="btn_search"><i class="fa-solid fa-magnifying-glass"></i> 검색</button>
              </div>
            </div>
          </div>
          <div class="row">
            {% if sell_list %}
            {% for sell in sell_list %}
            {% comment %} {% for sell in user.voter_sell.all %} {% endcomment %}
              <div class="col-3">
                <div class="card" style="margin: 3px;">
                  <img class="sellpic" src="https://randomuser.me/api/portraits/men/{{sell.author.id}}.jpg">
                  <div class="card-body">
                    <a class="stretched-link" style="color:black;" href="{% url 'joonggo:detail' sell.id %}">{{ sell.subject }}
                      {% if sell.comment_set.count %}
                        <span class="ml-2">
                          <i class="fa-regular fa-comment-dots"></i>
                          <span>{{sell.comment_set.count}}</span>
                        </span>
                      {% endif %}
                    </a>
                    {% comment %} <p class="">{{ sell.price }}</p> {% endcomment %}
                    <p class="small"><img class="avatar" src="https://randomuser.me/api/portraits/men/{{sell.author.id}}.jpg"> {{ sell.author.username }}
                    </p>
                    {% if sell.voter.all.count >= 0 %}
                    좋아요<span class="text-danger px-2 py-1">
                    {% if user in sell.voter.all %}
                    <i class="fa-solid fa-heart"></i>
                    {% else %}
                    <i class="fa-regular fa-heart"></i>
                    {% endif %}
                  </span>
                {% endif %}
                    
                  </div>
                </div>
              </div>
            
            
            {% endfor %}
            {% endif %}
            

          </div>
        </div>
    {% include 'joonggo/pagenation.html' %}
    <a href="{% url 'joonggo:sell_create' %}" class="btn btn-primary">글 작성</a>
  </div>
</div>

<form id="searchForm" method="get" action="{% url 'index' %}">
  <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
  <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{% endblock content %}

{% block script %}
  <script type='text/javascript'>
    $(document).ready(function () {
      $(".page-link").on('click', function () {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
      });
      $("#btn_search").on('click', function () {
        $("#kw").val($(".kw").val());
        $("#page").val(1); // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
      });
    });
  const realUpload = document.querySelector('.real-upload');
  const upload = document.querySelector('.upload');
  upload.addEventListener('click', () => realUpload.click());
  </script>
  
{% endblock %}

templates/joonggo/sell_mylike.html
{% extends 'base.html' %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

{% block content %}

<div class="row ml-5 my-3">
  <div class="col-2">
    <div class='card'>
      <div class="card-body">
        {% if user.is_authenticated %}
        <div>회원정보</div>
        <img class="avatar" src="https://randomuser.me/api/portraits/men/{{user.id}}.jpg"> {{ user.username }}
        <div>
          <a style="color:black;" href="{% url 'joonggo:sell_mypost' user.id %}">내가 쓴 글 보기</a>
        </div>
        <div>
          <a style="color:black;" href="{% url 'joonggo:sell_mylike' user.id %}">좋아요 한 글 보기</a>
        </div>
        {% else %}
        <div>
        회원정보
        </div>
        <a style="font-size:14px;" class="nav-link" href="{% url 'common:login' %}">로그인이 필요합니다.</a>
        {% endif %}
      </div>
    </div>
  </div>
  
  <div class="col-8 mr-3">
    <table class="table">

      <tbody>
        

        <!-- 게시판 카드형식 만들기 -->
        <div class="container">
          <div class="row justify-content-center my-3">
            <div class="col-6 input-group">
              <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
              <div class="input-group-append">
                <button class="btn btn-outline-dark" type="button" id="btn_search"><i class="fa-solid fa-magnifying-glass"></i> 검색</button>
              </div>
            </div>
          </div>
          <div class="row">
            {% if sell_list %}
            {% for sell in sell_list %}
            <div class="col-3">
              <div href="{% url 'joonggo:detail' sell.id %}" class="card" style="margin: 3px;">
                <img class="sellpic" src="https://randomuser.me/api/portraits/men/{{sell.author.id}}.jpg">
                <div class="card-body">
                  <a class="stretched-link" style="color:black;" href="{% url 'joonggo:detail' sell.id %}">{{ sell.subject }}</a>
                  {% comment %} <p class="">{{ sell.price }}</p> {% endcomment %}
                  <p class="small"><img class="avatar" src="https://randomuser.me/api/portraits/men/{{sell.author.id}}.jpg"> {{ sell.author.username }}
                  </p>
                  {% if sell.voter.all.count >= 0 %}
                  좋아요<span class="text-danger px-2 py-1">
                  {% if user in sell.voter.all %}
                  <i class="fa-solid fa-heart"></i>
                  {% else %}
                  <i class="fa-regular fa-heart"></i>
                  {% endif %}
                </span>
              {% endif %}
                  
                </div>
              </div>
            </div>
            
            {% endfor %}
            {% endif %}
            

          </div>
        </div>
    {% include 'joonggo/pagenation.html' %}
    <a href="{% url 'joonggo:sell_create' %}" class="btn btn-primary">글 작성</a>
  </div>
</div>

<form id="searchForm" method="get" action="{% url 'index' %}">
  <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
  <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{% endblock content %}

{% block script %}
  <script type='text/javascript'>
    $(document).ready(function () {
      $(".page-link").on('click', function () {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
      });
      $("#btn_search").on('click', function () {
        $("#kw").val($(".kw").val());
        $("#page").val(1); // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
      });
    });
  </script>
{% endblock %}

templates/joonggo/sell_mypost.html
{% extends 'base.html' %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

{% block content %}

<div class="row ml-5 my-3">
  <div class="col-2">
    <div class='card'>
      <div class="card-body">
        {% if user.is_authenticated %}
        <div>회원정보</div>
        <img class="avatar" src="https://randomuser.me/api/portraits/men/{{user.id}}.jpg"> {{ user.username }}
        <div>
          <a style="color:black;" href="{% url 'joonggo:sell_mypost' user.id %}">내가 쓴 글 보기</a>
        </div>
        <div>
          <a style="color:black;" href="{% url 'joonggo:sell_mylike' user.id %}">좋아요 한 글 보기</a>
        </div>
        {% else %}
        <div>
        회원정보
        </div>
        <a style="font-size:14px;" class="nav-link" href="{% url 'common:login' %}">로그인이 필요합니다.</a>
        {% endif %}
      </div>
    </div>
  </div>
  
  <div class="col-8 mr-3">
    <table class="table">

      <tbody>
        

        <!-- 게시판 카드형식 만들기 -->
        <div class="container">
          <div class="row justify-content-center my-3">
            <div class="col-6 input-group">
              <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
              <div class="input-group-append">
                <button class="btn btn-outline-dark" type="button" id="btn_search"><i class="fa-solid fa-magnifying-glass"></i> 검색</button>
              </div>
            </div>
          </div>
          <div class="row">
            {% if sell_list %}
            {% for sell in sell_list %}
            <div class="col-3">
              <div href="{% url 'joonggo:detail' sell.id %}" class="card" style="margin: 3px;">
                <img class="sellpic" src="https://randomuser.me/api/portraits/men/{{sell.author.id}}.jpg">
                <div class="card-body">
                  <a class="stretched-link" style="color:black;" href="{% url 'joonggo:detail' sell.id %}">{{ sell.subject }}</a>
                  {% comment %} <p class="">{{ sell.price }}</p> {% endcomment %}
                  <p class="small"><img class="avatar" src="https://randomuser.me/api/portraits/men/{{sell.author.id}}.jpg"> {{ sell.author.username }}
                  </p>
                  {% if sell.voter.all.count >= 0 %}
                  좋아요<span class="text-danger px-2 py-1">
                  {% if user in sell.voter.all %}
                  <i class="fa-solid fa-heart"></i>
                  {% else %}
                  <i class="fa-regular fa-heart"></i>
                  {% endif %}
                </span>
              {% endif %}
                  
                </div>
              </div>
            </div>
            
            {% endfor %}
            {% endif %}
            

          </div>
        </div>
    {% include 'joonggo/pagenation.html' %}
    <a href="{% url 'joonggo:sell_create' %}" class="btn btn-primary">글 작성</a>
  </div>
</div>

<form id="searchForm" method="get" action="{% url 'index' %}">
  <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
  <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{% endblock content %}

{% block script %}
  <script type='text/javascript'>
    $(document).ready(function () {
      $(".page-link").on('click', function () {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
      });
      $("#btn_search").on('click', function () {
        $("#kw").val($(".kw").val());
        $("#page").val(1); // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
      });
    });
  </script>
{% endblock %}